blueprint:
  name: Synchronize Open and Closing Group of shades
  description: Synchronize the open/close state of a group of shades
  domain: automation
  input:
    target_shades:
      name: Target Shades
      selector:
        entity:
          filter:
          - domain:
            - cover
          multiple: true
  source_url: https://github.com/jvmahon/HomeAssistant-Tools/blob/main/synchronize_shade_group.yaml
variables:
  shade_group: !input target_shades
triggers:
  - trigger: state
    entity_id: !input target_shades
    to:
      - open
      - opening
    variables:
      shade_entities: !input target_shades
    id: Opening
  - trigger: state
    entity_id: !input target_shades
    to:
      - closed
      - closing
    variables:
      shade_entities: !input target_shades
    id: Closing
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Opening
        sequence:
          - action: cover.open
            target:
              entity_id:  >-
                {{ !input target_shades | reject('is_state', 'open') |
                reject('is_state', 'opening') | list}}
      - conditions:
          - condition: trigger
            id:
              - Closing
        sequence:
          - action: cover.close
            target:
              entity_id: !input target_shades
mode: single
